const $ = (s, el = document) => el.querySelector(s);
const $$ = (s, el = document) => [...el.querySelectorAll(s)];
const auth = $('#auth'), app = $('#app'), main = $('#main'), modal = $('#modal'), modalBody = $('#modalBody'), toast = $('#toast'), sidebar = $('#sidebar');
let state = null, csrf = null, catalog = null, sessionBusy = false;
const titles = {today:'TODAY', skills:'SKILLS', challenges:'CHALLENGES', proof:'PROOF VAULT', progress:'PROGRESS', settings:'SETTINGS'};
const fallback = {software:['Ship one tiny interaction','BUILD',25,30],writing:['Write 300 useful words','WRITE',25,30],design:['Fix one hierarchy problem','DESIGN',30,30],fitness:['Complete a focused session','TRAIN',30,30],language:['Speak for five minutes','SPEAK',20,15],money:['Audit one spending pattern','REVIEW',25,20]};
function esc(v){return String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toastMsg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove('show'),2400)}
async function api(path, opts={}){const r=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function track(name, properties={}){try{await api('/api/analytics',{method:'POST',headers:{'X-CSRF-Token':csrf},body:JSON.stringify({name,properties})})}catch{} }
function currentView(){const v=(location.hash||'#today').slice(1).split('?')[0];return titles[v]?v:'today'}
function activeSkill(){return state?.skills?.find(s=>s.slug===state.profile.active_skill_id) || state?.skills?.[0]}
function missionFor(s){const items=(catalog?.missions||[]).filter(m=>m[0]===s.slug || m[0]===s.category.toLowerCase()); const list=items.length?items:fallback[s.slug] ? [[s.slug,...fallback[s.slug]]] : [['software','Ship one tiny interaction','Build one complete interaction.','BUILD',25,30,'free']]; const idx=(state.profile.missions_completed||0)%list.length; return list[idx]}
function initials(name){return (name||'S').split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function shell(){auth.classList.add('hidden');app.classList.remove('hidden');sidebar.classList.remove('hidden');renderSidebar();render();}
function renderSidebar(){const v=currentView(), s=activeSkill(); sidebar.innerHTML=`<div class="sidebar-head"><span class="kicker">YOUR SYSTEM</span><button class="icon-btn" id="closeNav">×</button></div><nav>${Object.entries(titles).map(([k,t],i)=>`<a data-nav class="nav ${v===k?'active':''}" href="#${k}"><span>${['01','02','03','04','05','06'][i]}</span>${t}</a>`).join('')}</nav><div class="side-card"><span class="kicker">ACTIVE SKILL</span><strong>${esc(s?.name||'Choose a skill')}</strong><span>${esc(s?.category||'')}</span></div><div class="side-foot"><span class="kicker">PLAN</span><strong>${esc(state?.user?.plan==='plus'?'FORGE+':'FREE')}</strong><small>${state?.user?.email_verified?'Verified account':'Local prototype account'}</small></div>`; $$('#closeNav').forEach(b=>b.onclick=()=>sidebar.classList.remove('mobile-open'));}
function pageHead(kicker,title,lede,actions=''){return `<div class="page-head"><div><div class="kicker">${kicker}</div><h1>${title}</h1><p class="lede">${lede}</p></div><div class="head-actions">${actions}</div></div>`}
function todayView(){const s=activeSkill(),m=missionFor(s),p=state.profile, logged=state.events.filter(e=>e.type==='practice_log'||e.type==='mission_complete').reduce((a,e)=>a+(e.minutes||0),0); const daily=Math.min(100,Math.round((Math.min(logged,p.daily_goal)/p.daily_goal)*100)); return pageHead('TODAY\'S REP','Practice the thing you said mattered.','One deliberate session. One visible result. Then stop.',`<button class="ghost" id="openUpgrade">${state.user.plan==='plus'?'FORGE+ ACTIVE':'Unlock Forge+'}</button>`) + `<section class="mission-card"><div class="mission-top"><span class="tag">${esc(m[3]||m[2])}</span><span>${Number(m[5]||30)} MIN</span><span>+${Number(m[4]||m[2])} XP</span></div><div class="mission-grid"><div><div class="mission-eyebrow">ACTIVE MISSION</div><h2>${esc(m[1]||m[0])}</h2><p>${esc(m[2]||'Complete a focused rep and record what changed.')}</p></div><div class="mission-visual"><div class="ring" style="--p:${daily}%"><strong>${daily}%</strong><span>today</span></div></div></div><div class="mission-bottom"><span>Active skill: <b>${esc(s.name)}</b></span><button class="primary" id="complete">Complete rep ↗</button></div></section><div class="stat-grid"><div class="stat"><span>XP</span><strong>${p.xp.toLocaleString()}</strong><small>earned on account</small></div><div class="stat"><span>STREAK</span><strong>${p.streak}</strong><small>consecutive practice days</small></div><div class="stat"><span>REPS</span><strong>${p.missions_completed}</strong><small>completed missions</small></div><div class="stat"><span>TIME</span><strong>${logged}m</strong><small>practice recorded</small></div></div><div class="split"><section class="panel"><div class="panel-head"><div><div class="kicker">NEXT MOVE</div><h3>Make the result visible</h3></div><span class="score">${state.proofs.length}</span></div><p>Save a screenshot, link, note, recording, or result after the rep. Evidence turns effort into a history you can revisit.</p><a class="text-link" href="#proof">Open proof vault →</a></section><section class="panel dark"><div class="panel-head"><div><div class="kicker">PRACTICE LOG</div><h3>Add time outside missions</h3></div><button class="secondary light" id="logTime">+ Add time</button></div><p>Your plan measures consistency without forcing everything into a challenge.</p></section></div>`}
function skillsView(){return pageHead('SKILL SYSTEM','Build a few skills deeply.','Every skill gets reps, proof, and a visible history.',`<button class="primary" id="newSkill">+ Add skill</button>`) + `<div class="skill-grid">${state.skills.map(s=>`<article class="skill-card ${s.slug===state.profile.active_skill_id?'chosen':''}"><div class="skill-line"><span class="skill-dot"></span><span class="tag">${esc(s.category)}</span>${s.slug.startsWith('custom-')?'<span class="custom">CUSTOM</span>':''}</div><h3>${esc(s.name)}</h3><div class="bar"><i style="width:${s.progress}%"></i></div><div class="skill-meta"><span>${s.progress}% depth</span><span>${s.reps} reps</span></div><div class="skill-actions"><button class="secondary full" data-focus="${esc(s.slug)}">${s.slug===state.profile.active_skill_id?'Active skill':'Focus this skill'} →</button>${s.slug.startsWith('custom-')?`<button class="icon-btn" title="Delete skill" data-skill-delete="${s.id}">×</button>`:''}</div></article>`).join('')}</div>`}
function challengesView(){const cs=catalog?.challenges||[];return pageHead('CHALLENGES','Constraints create momentum.','Short campaigns that make practice easier to start.') + `<div class="challenge-list">${cs.map(c=>{const active=state.challenges.some(x=>x.challenge_id===c[0]);const locked=c[6]==='plus'&&state.user.plan!=='plus';return `<article class="challenge"><div class="challenge-badge">${c[3]}d</div><div class="challenge-body"><div class="challenge-row"><span class="tag">${esc(c[5])}</span>${c[6]==='plus'?'<span class="plus-tag">FORGE+</span>':''}</div><h3>${esc(c[1])}</h3><p>${esc(c[2])}</p><div class="challenge-foot"><span>Reward +${c[4]} XP</span>${active?'<b class="started">Started</b>':locked?'<button class="secondary" data-challenge-upgrade>Unlock →</button>':`<button class="secondary" data-challenge="${esc(c[0])}">Start challenge →</button>`}</div></div></article>`}).join('')}</div>`}
function proofView(){return pageHead('PROOF VAULT','Keep evidence, not intentions.','A private record of things you actually finished.',`<button class="primary" id="newProof">+ Save proof</button>`) + `<div class="proofs">${state.proofs.length?state.proofs.map(p=>`<article class="proof"><div class="proof-mark">✓</div><div><div class="proof-line"><span class="tag">${esc(p.kind)}</span><time>${new Date(p.created_at*1000).toLocaleDateString()}</time></div><h3>${esc(p.title)}</h3><p>${esc(p.note||'No note added.')}</p></div><button class="icon-btn" data-delete="${p.id}">×</button></article>`).join(''):`<div class="empty"><strong>Your vault is empty.</strong><span>Finish one rep, then save what changed.</span></div>`}</div>`}
function progressView(){const p=state.profile, events=state.events.filter(e=>e.minutes), mins=events.reduce((a,e)=>a+(e.minutes||0),0), week=events.filter(e=>e.created_at>Math.floor(Date.now()/1000)-7*86400).reduce((a,e)=>a+(e.minutes||0),0), proofs=state.proofs.length; const milestones=[[p.missions_completed>=1,'First rep','Complete one mission'],[p.missions_completed>=10,'Ten reps','Build a small body of work'],[p.streak>=7,'Seven-day streak','Practice on seven consecutive days'],[proofs>=5,'Five proof items','Document five finished results']];return pageHead('PROGRESS','Measure the work.','The useful numbers are reps, minutes, streaks, and finished artifacts.')+`<div class="progress-grid"><section class="panel big"><div class="kicker">TOTAL PRACTICE</div><strong class="giant">${mins}</strong><span class="muted">minutes logged on this account</span><div class="progress-duo"><div><b>${week}</b><span>this week</span></div><div><b>${proofs}</b><span>proof items</span></div></div></section><section class="panel big"><div class="kicker">MILESTONES</div>${milestones.map(m=>`<div class="milestone"><strong>${m[0]?'✓':'○'}</strong><span><b>${m[1]}</b><small>${m[2]}</small></span></div>`).join('')}</section></div>`}
function settingsView(){return pageHead('SETTINGS','Keep the system simple.','Control your practice target, data, and account.')+`<section class="settings-panel"><div class="setting"><div><b>Daily practice target</b><small>Minutes used to measure consistency.</small></div><input id="goal" type="number" min="5" max="240" value="${state.profile.daily_goal}"><button class="secondary" id="saveGoal">Save</button></div><div class="setting"><div><b>Account email</b><small>${esc(state.user.email)}</small></div><span class="badge">${state.user.email_verified?'VERIFIED':'NOT VERIFIED'}</span></div><div class="setting"><div><b>Subscription</b><small>${state.user.plan==='plus'?'Forge+ is active on this account.':'Free plan. Premium challenges stay locked.'}</small></div><button class="secondary" id="settingsUpgrade">${state.user.plan==='plus'?'Manage':'Upgrade'}</button></div><div class="setting"><div><b>Export account data</b><small>Download a JSON snapshot of your account.</small></div><button class="secondary" id="export">Export</button></div><div class="setting"><div><b>Reset password</b><small>Request a recovery link for this account.</small></div><button class="secondary" id="recovery">Send link</button></div><div class="setting danger-row"><div><b>Sign out</b><small>Clear the current browser session.</small></div><button class="danger" id="logout">Sign out</button></div></section>`}
function authView(message=''){sidebar.classList.add('hidden');app.classList.add('hidden');auth.classList.remove('hidden');auth.innerHTML=`<div class="auth-wrap"><div class="auth-card"><div class="auth-brand"><span class="logo">S</span><span>SkillForge</span></div><div class="kicker">BUILD THE SKILL. KEEP THE PROOF.</div><h1>Practice with intent.</h1><p>SkillForge turns vague goals into deliberate reps, visible progress, and a private record of what you actually finished.</p>${message?`<div class="error">${esc(message)}</div>`:''}<form id="loginForm"><label>Email<input id="email" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>Password<input id="password" type="password" autocomplete="current-password" minlength="8" required placeholder="8+ characters"></label><button class="primary wide" type="submit">Sign in</button></form><div class="auth-links"><button id="registerBtn" class="ghost">Create account</button><button id="forgotBtn" class="ghost">Forgot password?</button></div><button class="secondary wide" id="demoBtn">Try the demo account</button><small class="auth-note">Private beta build. Public launch uses HTTPS, hosted storage, verified email, abuse controls, backups, and configured billing.</small></div><div class="auth-side"><span class="kicker">THE LOOP</span><div class="loop"><b>01</b><span>Choose one skill</span><b>02</b><span>Do one deliberate rep</span><b>03</b><span>Save the proof</span><b>04</b><span>Come back tomorrow</span></div></div></div>`;$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({email:$('#email').value,password:$('#password').value})});csrf=d.csrf;state=d.state;track('login_complete');postLogin();}catch(err){authView(err.message)}};$('#registerBtn').onclick=registerView;$('#forgotBtn').onclick=forgotView;$('#demoBtn').onclick=async()=>{try{const d=await api('/api/demo',{method:'POST'});csrf=d.csrf;state=d.state;postLogin();toastMsg('Demo account loaded')}catch(e){authView(e.message)}}}
function registerView(){auth.innerHTML=`<div class="auth-card compact"><div class="auth-brand"><span class="logo">S</span><span>SkillForge</span></div><div class="kicker">NEW ACCOUNT</div><h1>Start with one skill.</h1><p>Make a local account now. The same model can later sit behind hosted auth and email verification.</p><form id="regForm"><label>Name<input id="rname" required placeholder="Your name" autocomplete="name"></label><label>Email<input id="remail" type="email" required placeholder="you@example.com" autocomplete="email"></label><label>Password<input id="rpass" type="password" minlength="8" required placeholder="8+ characters" autocomplete="new-password"></label><button class="primary wide" type="submit">Create account</button></form><button class="ghost wide" id="back">Back to sign in</button></div>`;$('#regForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/register',{method:'POST',body:JSON.stringify({name:$('#rname').value,email:$('#remail').value,password:$('#rpass').value})});csrf=d.csrf;state=d.state;postLogin();showOnboarding(true)}catch(err){registerView();toastMsg(err.message)}};$('#back').onclick=authView}
function forgotView(){auth.innerHTML=`<div class="auth-card compact"><div class="auth-brand"><span class="logo">S</span><span>SkillForge</span></div><div class="kicker">ACCOUNT RECOVERY</div><h1>Get a reset link.</h1><p>We'll prepare a recovery link. With email configured, it is sent to the account. In local dev mode the token is shown directly.</p><form id="forgotForm"><label>Email<input id="femail" type="email" required placeholder="you@example.com"></label><button class="primary wide">Prepare recovery</button></form><button class="ghost wide" id="back">Back to sign in</button></div>`;$('#forgotForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/recovery/request',{method:'POST',body:JSON.stringify({email:$('#femail').value})});if(d.dev_recovery_token){openReset(d.dev_recovery_token)}else{toastMsg(d.message);authView()}}catch(err){toastMsg(err.message)}};$('#back').onclick=authView}
function resetView(token){auth.innerHTML=`<div class="auth-card compact"><div class="auth-brand"><span class="logo">S</span><span>SkillForge</span></div><div class="kicker">PASSWORD RESET</div><h1>Create a new password.</h1><form id="resetForm"><label>New password<input id="newpass" type="password" minlength="8" required placeholder="8+ characters"></label><button class="primary wide">Reset password</button></form></div>`;$('#resetForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('/api/recovery/reset',{method:'POST',body:JSON.stringify({token,password:$('#newpass').value})});toastMsg(d.message);authView()}catch(err){toastMsg(err.message)}}}
function openReset(token){resetView(token)}
function postLogin(){shell();if(!state.user.onboarding_complete)showOnboarding(false);}
function showOnboarding(fromRegistration){openModal(`<div class="kicker">${fromRegistration?'WELCOME':'SETUP'}</div><h2>Build your first practice system.</h2><p>Pick the skill you want visible every day and set a small target you can actually repeat.</p><label>Your display name<input id="onName" value="${esc(state.user.name)}"></label><label>Active skill<select id="onSkill">${state.skills.map(s=>`<option value="${esc(s.slug)}" ${s.slug===state.profile.active_skill_id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Daily target <span class="muted">minutes</span><input id="onGoal" type="number" min="5" max="240" value="${state.profile.daily_goal}"></label><div class="modal-actions"><button class="primary" id="finishOnboarding">Build my system →</button></div>`);$('#finishOnboarding').onclick=async()=>{await mutate('/api/onboarding',{name:$('#onName').value,activeSkill:$('#onSkill').value,dailyGoal:Number($('#onGoal').value)||25});closeModal();render();track('onboarding_finished');toastMsg('Your system is ready');}
function openUpgrade(){openModal(`<div class="kicker">FORGE+</div><h2>Turn practice into a subscription people understand.</h2><p>Forge+ is the premium layer: deeper challenges, extended history, and room for a more ambitious practice system. The local build never fakes a successful payment.</p><div class="plans"><div><strong>FREE</strong><span>Core missions</span><span>Proof vault</span><span>Progress</span></div><div class="featured"><strong>FORGE+</strong><span>Premium challenges</span><span>Extended history</span><span>Priority features</span></div></div><p class="price">Suggested test price <b>$8.99/month</b> or <b>$59.99/year</b></p><div class="modal-actions"><button class="secondary" data-close>Not now</button><button class="primary" id="checkout">Open checkout ↗</button></div>`);$('#checkout').onclick=async()=>{try{const d=await api('/api/checkout',{method:'POST',headers:{'X-CSRF-Token':csrf},body:'{}'});location.href=d.url}catch(e){toastMsg(e.message)}}}
}
function openModal(html){modalBody.innerHTML=html;modal.classList.remove('hidden');$$('[data-close]',modal).forEach(x=>x.onclick=closeModal)}function closeModal(){modal.classList.add('hidden')}
async function mutate(path,payload){const d=await api(path,{method:'POST',headers:{'X-CSRF-Token':csrf},body:JSON.stringify(payload)});if(d.state)state=d.state;renderSidebar();return d}
function bind(){
  $$('[data-focus]').forEach(b=>b.onclick=async()=>{await mutate('/api/profile',{activeSkill:b.dataset.focus});location.hash='#today';render();toastMsg('Active skill changed')});
  $('#complete')?.addEventListener('click',async()=>{const s=activeSkill(),m=missionFor(s);const minutes=Number(m[5]||30),xp=Number(m[4]||25);await mutate('/api/mission/complete',{skillId:s.id,mission:m[1]||m[0],minutes,xp});track('rep_completed',{skill:s.slug});toastMsg(`+${xp} XP · rep complete`);render()});
  $('#logTime')?.addEventListener('click',()=>openModal(`<div class="kicker">PRACTICE LOG</div><h2>Add focused time.</h2><label>Minutes<input id="mins" type="number" min="1" max="480" value="25"></label><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="save">Save time</button></div>`));
  $('#save')?.addEventListener('click',async()=>{await mutate('/api/time',{minutes:Number($('#mins').value)||1,skillId:activeSkill().slug});closeModal();toastMsg('Practice logged');render()});
  $('#newProof')?.addEventListener('click',()=>openModal(`<div class="kicker">PROOF VAULT</div><h2>Save something real.</h2><label>Title<input id="pt" placeholder="What did you finish?"></label><label>Type<select id="pk"><option>PROJECT</option><option>CODE</option><option>PHOTO</option><option>RESULT</option><option>NOTE</option></select></label><label>Note<textarea id="pn" placeholder="What changed?"></textarea></label><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="saveP">Save proof</button></div>`));
  $('#saveP')?.addEventListener('click',async()=>{await mutate('/api/proof',{title:$('#pt').value,kind:$('#pk').value,note:$('#pn').value});closeModal();track('proof_saved');toastMsg('Proof saved');render()});
  $$('[data-delete]').forEach(e=>e.onclick=async()=>{if(confirm('Delete this proof?')){await mutate('/api/proof/delete',{id:Number(e.dataset.delete)});toastMsg('Proof deleted');render()}});
  $$('[data-challenge]').forEach(e=>e.onclick=async()=>{try{await mutate('/api/challenge/start',{id:e.dataset.challenge});toastMsg('Challenge started');render()}catch(err){toastMsg(err.message)}});
  $$('[data-challenge-upgrade]').forEach(e=>e.onclick=openUpgrade);
  $('#newSkill')?.addEventListener('click',()=>openModal(`<div class="kicker">NEW SKILL</div><h2>Name the skill.</h2><label>Name<input id="sn" placeholder="e.g. Draw portraits"></label><label>Category<input id="sc" placeholder="ART"></label><div class="modal-actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="saveSkill">Add skill</button></div>`));
  $('#saveSkill')?.addEventListener('click',async()=>{try{await mutate('/api/skill',{action:'create',name:$('#sn').value,category:$('#sc').value});closeModal();toastMsg('Skill added');render()}catch(e){toastMsg(e.message)}});
  $$('[data-skill-delete]').forEach(e=>e.onclick=async()=>{if(confirm('Delete this custom skill?')){try{await mutate('/api/skill',{action:'delete',id:Number(e.dataset.skillDelete)});toastMsg('Skill deleted');render()}catch(err){toastMsg(err.message)}}});
  $('#saveGoal')?.addEventListener('click',async()=>{await mutate('/api/profile',{dailyGoal:Number($('#goal').value)||25});toastMsg('Daily target saved');render()});
  $('#export')?.addEventListener('click',async()=>{const d=await api('/api/export',{method:'POST',headers:{'X-CSRF-Token':csrf},body:'{}'});const a=document.createElement('a');a.href='data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(d.state,null,2));a.download='skillforge-account.json';a.click();track('account_exported');toastMsg('Export created')});
  $('#logout')?.addEventListener('click',async()=>{await api('/api/logout',{method:'POST',headers:{'X-CSRF-Token':csrf},body:'{}'});state=null;csrf=null;authView();toastMsg('Signed out')});
  $('#settingsUpgrade')?.addEventListener('click',openUpgrade); $('#openUpgrade')?.addEventListener('click',openUpgrade); $('#upgradeBtn').onclick=openUpgrade;
  $('#recovery')?.addEventListener('click',async()=>{const d=await api('/api/recovery/request',{method:'POST',body:JSON.stringify({email:state.user.email})});if(d.dev_recovery_token)openReset(d.dev_recovery_token);else toastMsg(d.message)});
  $('#menuBtn')?.addEventListener('click',()=>sidebar.classList.toggle('mobile-open'));
}
function render(){if(!state)return;const view=currentView();$('#sectionName').textContent=titles[view];renderSidebar();const fn={today:todayView,skills:skillsView,challenges:challengesView,proof:proofView,progress:progressView,settings:settingsView}[view];main.innerHTML=fn();$('#avatar').textContent=initials(state.user.name);$('#syncBadge').textContent=state.user.plan==='plus'?'FORGE+':'SERVER';bind()}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));}
async function boot(){try{const d=await api('/api/me');if(d.authenticated){csrf=d.csrf;state=d.state;const c=await api('/api/catalog');catalog=c;shell();}else{catalog=await api('/api/catalog');authView();}}catch(e){authView('The local server did not respond. Start server.py and refresh.')}}
window.addEventListener('hashchange',()=>{renderSidebar();render()});
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(!e.ctrlKey&&!e.metaKey&&!e.altKey){const n=Number(e.key);const links=['today','skills','challenges','proof','progress'];if(n>=1&&n<=5)location.hash='#'+links[n-1]}});
boot();
